identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - id

opt_in_rules:
 - indentation_width
 - explicit_self
 - operator_usage_whitespace
 - line_length:

disabled_rules:
  - line_length
  - trailing_whitespace
